### PR TITLE
chore: update changelog(5.9.48)

### PR DESCRIPTION
**Pull request by hundundadi**
Description: update changelog(5.9.48)

Log: update changelog(5.9.48)

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
