### PR TITLE
fix: 修改调试模式配置文件的默认值

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 修改调试模式配置文件的默认值

Log: 修改调试模式配置文件的默认值

Bug: https://pms.uniontech.com/bug-view-238907.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]

**Review by wyu71 — COMMENTED** [review]
/+1

**Pull request merged**
