### PR TITLE
chore: Update translation

### PR DESCRIPTION
**Pull request by mhduiy**
kill -> terminate
杀死 -> 终止

Issue: https://github.com/linuxdeepin/developer-center/issues/9394

### CODE REVIEW

**Review by ArchieMeng — CHANGES_REQUESTED** [review]
可以添加一下繁体的翻译

**Comment by mhduiy** [comment]
> 可以添加一下繁体的翻译

OK啦

**Review by ArchieMeng — APPROVED** [review]
+1

**Pull request merged**
