### PR TITLE
fix: The application name is incorrectly written

### PR DESCRIPTION
**Pull request by hundundadi**
Description: The application name is incorrectly written

Log: The application name is incorrectly written

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Review by hundundadi — COMMENTED** [review]
/merge

**Pull request merged**
