### PR TITLE
chore: Bump version to 5.9.45

### PR DESCRIPTION
**Pull request by rb-union**
Bump version to 5.9.45
PR:
* https://github.com/linuxdeepin/deepin-terminal/pull/310

Log: Bump version to 5.9.45

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
