### PR TITLE
fix: compile error

### PR DESCRIPTION
**Pull request by rb-union**
Fix cimpile error: header file not included.

Log: fix compile error

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by starhcq — APPROVED** [review]
/+1

**Pull request merged**
